### ISSUE TITLE
Greek Etymological Dictionary Incomplete?

### ISSUE THREAD

**Issue by jiang-qian** [yozhic/DSL-Reference#1]
Dear Developer, 

from this website
https://latin-dict.github.io/dictionaries/morphology-grc.html
I find a repository of greek dictionaries that includes not just morphological dictionary but also Greek Etymological Dictionary. The acknowledgement is given to "yozhic", which led me here.

If you are indeed the provider of that dictionary, I thank you for your service! However, I do that the etymological dictionary is incomplete. Do you happen to have the more complete version or know where I can find it? Thank you in advance!

**Comment by yozhic** [comment]
I apologize for the huge delay in replying. I am not a developer in this case. I converted the Morphologia Graeca dictionary to DSL format from the free [Perseus Hopper database](http://www.perseus.tufts.edu/hopper/morph). It differs from the source only in format. I think you can find many examples of this kind of conversion on the Internet, which will be better than my attempt.
